export interface TimetableEntry {
  day: string;
  startTime: string;
  endTime: string;
  group: string;
  subject: string;
  teacher: string;
  room: string;
}

export const timetable: TimetableEntry[] = [
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПИМ-1-24',
    subject: 'Русский язык',
    teacher: 'Омуркулова Г.М.',
    room: '413',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПОВТ-1-24',
    subject: 'Математика',
    teacher: 'Салиева Ф.',
    room: '409',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПОВТ-2-24',
    subject: 'Физика',
    teacher: 'Нарманбетова Г. Ж.',
    room: '338',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПОВТ-3-24',
    subject: 'Математика',
    teacher: 'Алыкулова К.Б',
    room: '407',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПОВТ-4-24',
    subject: 'Backend',
    teacher: 'Маликов А. Р.',
    room: '402',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПОАС-1-24',
    subject: 'Введение в специальность',
    teacher: 'Каныбеков М.О.',
    room: '406',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПОАС-2-24',
    subject: 'Frontend',
    teacher: 'Айдаров А. И.',
    room: '404',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ДПО-1-24',
    subject: 'Кыргыз тил',
    teacher: 'Шапкулова А.А.',
    room: '405',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ДПО-2-24',
    subject: 'Backend',
    teacher: 'Кыдырмышев А.Б.',
    room: '403',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПИ-1-24',
    subject: 'Физ. культура',
    teacher: 'Асанов Т.О.',
    room: 'сп.зал',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '7:30',
    endTime: '8:50',
    group: 'ПИ-2-24',
    subject: 'Backend',
    teacher: 'Зарипбеков Т. К.',
    room: '408',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПИМ-1-24',
    subject: 'Математика',
    teacher: 'Салиева Ф. С.',
    room: '409',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПОВТ-1-24',
    subject: 'Физ. к��льтура',
    teacher: 'Асанов Т.О.',
    room: 'сп.зал',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПОВТ-2-24',
    subject: 'Иностранный язык',
    teacher: 'Балбаева Э.К.',
    room: '412',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПОВТ-3-24',
    subject: 'История Кыргызстана',
    teacher: 'Ибраимова А.Т.',
    room: '418',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПОВТ-4-24',
    subject: 'Математика',
    teacher: 'Алыкулова К.Б',
    room: '407',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПОАС-1-24',
    subject: 'Физика',
    teacher: 'Нарманбетова Г. Ж.',
    room: '338',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПОАС-2-24',
    subject: 'Кыргыз тил',
    teacher: 'Шапкулова А.А.',
    room: '405',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ДПО-1-24',
    subject: 'Backend',
    teacher: 'Кыдырмышев А.Б.',
    room: '403',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ДПО-2-24',
    subject: 'Физ. культура',
    teacher: 'Асанов Т.О.',
    room: 'сп.зал',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПИ-1-24',
    subject: 'Русский язык',
    teacher: 'Омуркулова Г.М.',
    room: '413',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '9:00',
    endTime: '10:30',
    group: 'ПИ-2-24',
    subject: 'Введение в специальность (основы IT)',
    teacher: 'Каныбеков М.О.',
    room: '406',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПИМ-1-24',
    subject: 'История Кыргызстана',
    teacher: 'Ибраимова А.Т.',
    room: '418',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПОВТ-1-24',
    subject: 'Backend',
    teacher: 'Каримов Э.Р.',
    room: '402',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПОВТ-2-24',
    subject: 'Физ. культура',
    teacher: 'Асанов Т.О.',
    room: 'сп.зал',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПОВТ-3-24',
    subject: 'Иностранный язык',
    teacher: 'Балбаева Э.К.',
    room: '412',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПОВТ-4-24',
    subject: 'Frontend',
    teacher: 'Шаршебаев А. М.',
    room: '406',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПОАС-1-24',
    subject: 'Математика',
    teacher: 'Салиева Ф.',
    room: '409',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПОАС-2-24',
    subject: 'Русский язык',
    teacher: 'Омуркулова Г.М.',
    room: '413',
  },
  {
    day: 'П��НЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ДПО-1-24',
    subject: 'Физика',
    teacher: 'Нарманбетова Г. Ж.',
    room: '338',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ДПО-2-24',
    subject: 'Кыргыз тил',
    teacher: 'Шапкулова А.А.',
    room: '405',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПИ-1-24',
    subject: 'Математика',
    teacher: 'Алыкулова К.Б',
    room: '407',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '10:30',
    endTime: '12:10',
    group: 'ПИ-2-24',
    subject: 'Физ. культура',
    teacher: 'Асанов Т.О.',
    room: 'сп.зал',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ПИМ-1-24',
    subject: 'Кыргыз тил',
    teacher: 'Шапкулова А.А.',
    room: '405',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ПОВТ-1-24',
    subject: 'Физика',
    teacher: 'Нарманбетова Г. Ж.',
    room: '338',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ПОВТ-2-24',
    subject: 'Frontend',
    teacher: 'Шаршебаев А. М.',
    room: '403',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ПОВТ-3-24',
    subject: 'Frontend',
    teacher: 'Айдаров А. И.',
    room: '406',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ПОВТ-4-24',
    subject: 'Backend',
    teacher: 'Зарипбеков Т. К.',
    room: '404',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ПОАС-1-24',
    subject: 'Иностранный язык',
    teacher: 'Балбаева Э.К.',
    room: '412',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ПОАС-2-24',
    subject: 'Исто��ия Кыргызстана',
    teacher: 'Ибраимова А.Т.',
    room: '418',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ДПО-1-24',
    subject: 'Математика',
    teacher: 'Алыкулова К.Б',
    room: '407',
  },
  {
    day: 'ПОНЕДЕЛЬНИК',
    startTime: '12:10',
    endTime: '13:50',
    group: 'ДПО-2-24',
    subject: 'Русский язык',
    teacher: 'Омуркулова Г.М.',
    room: '413',
  },
  // Добавьте остальные записи аналогичным образом для всех дней недели
];
